openapi: 3.1.0
info:
  version: 0.0.1
  title: Leagueify League API
  summary: Open Source Sporting League Platform.
  description: '
    The Leagueify league service is responsible for managing user
    authentication, authorization, and profiles.
    '
  license:
    name: MIT
    url: https://raw.githubusercontent.com/Leagueify/league/main/LICENSE
  contact:
    name: Leagueify Support
    url: https://github.com/Leagueify/league/issues

servers:
  - url: http://localhost:6503/league
    description: Local Docker Development

paths:
  /healthz:
    get:
      tags:
      - Health Check
      summary: League Service Health Check
      description: '
        Check the health status of the Leagueify League service. This endpoint
        should return the service name and a status of ok.
        '
      responses:
        200:
          description: Health Check Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    description: Service Name
                    type: string
                    example: league
                  status:
                    description: Server HTTP Status
                    type: string
                    example: ok
